<?php

namespace AppBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAllOrderByName(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT student FROM AppBundle:Student ORDER BY student.firstname ASC'
            )
            ->getResult();
    }
}
