<?php

namespace AppBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function studentQuery(){

        $studentRepo = $this->getDoctrine()->getRepository('AppBundle:Student');
        return $this->render('student/unemethode.html.twig', [
            'students' => $studentRepo->uneMethode(),
        ]);
    }
}
