app_student_type:
    resource: "@AppBundle/Controller/StudentTypeController.php"
    type:     annotation

app_student:
    resource: "@AppBundle/Controller/StudentController.php"
    type:     annotation

bunker:
    resource: "@BunkerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
